### ISSUE TITLE
Computation of the APLS metric

### ISSUE THREAD

**Issue by onvungocminh** [CosmiQ/apls#18]
Hi @avanetten, I have a question about the APLS metric. How to compute the APLS metric from the pixel-wise segmentation of the road? Thankin advance.

**Comment by avanetten** [comment]
APLS is a graph theoretic metric, so it's not designed to score pixel-wise segmentation.  In order to use APLS, you need to turn your segmentation mask into a graph, with something like CRESI (https://github.com/avanetten/cresi).  Best of luck.
